p/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html\

  get '/mypage' => 'main#mypage'
  get '/answers' => 'main#answers'
  get '/destination' => 'main#destination'
  get '/tvshows' => 'main#tvshows'
  get '/music' => 'main#music'
  get '/number/:num' => 'main#number'
  get '/divisible/:num1&:num2' => 'main#divisible'
  get '/stringchar/:str' => 'main#stringchar'
  root to: 'main#answers'

end

p/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

p/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

p/app/controllers/main_controller.rb
class MainController < ApplicationController
    def answers
        @jesus_answers  = ["rya house",
        "ryan house", "ryans house"]
        render 'answers.html.erb'
    end
    def mypage
        render html: "Ryan <3 Jesus"
    end
    def destination
        @jesus_destinations = ["rya overseas house","ryan overseas house", "ryans overseas house"]
        render 'destination.html.erb'
    end
    def tvshows
        @jesus_shows= ["ET", "ET2", "ET3"]
        render 'tvshows.html.erb'
    end
    def music
        @music = params[:music]
        render 'music.html.erb'
    end
    def number
        @num = params[:num].to_i
        @num = @num ** 3
        render 'number.html.erb'
    end
    def divisible
        @num1 = params[:num1].to_i
        @num2 = params[:num2].to_i
        @mid_string = @num1 % @num2 == 0 ? ' is divisble by ' : ' is not divisible by '
        render 'divisible.html.erb'
    end
    def stringchar
        @str = params[:str].to_s
        @strcount = @str.length
        render 'stringchar.html.erb'
    end
end

p/app/helpers/application_helper.rb
module ApplicationHelper
end

p/app/helpers/main_helper.rb
module MainHelper
end

p/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mydbpractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

p/app/views/main/answers.html.erb
<%= form_tag(music_path, :method => "get") do %>
    <%= label_tag(:music, "What is your favorite song:") %>
    <%= text_field_tag(:music) %>
    <%= submit_tag("Go") %>
<% end %>



<ul>
    <li><%=link_to @jesus_answers[0], tvshows_path%></li>
    <li><%=@jesus_answers[1] %></li>
    <li><%=@jesus_answers[2] %></li>
</ul>

p/app/views/main/destination.html.erb
Ryans favorite movies:
    <ul>
        <li><%=@jesus_destinations[0] %></li>
        <li><%=@jesus_destinations[1] %></li>
        <li><%=@jesus_destinations[2] %></li>
    </ul>

p/app/views/main/divisible.html.erb
<%=@num1%> <%=@mid_string%> <%=@num2%>

p/app/views/main/music.html.erb
Your favorite song is: <%= @music %>
<p><%=link_to 'Return', answers_path%></p>

p/app/views/main/number.html.erb
<%=@num%>

p/app/views/main/stringchar.html.erb
<%= @strcount %>

p/app/views/main/tvshows.html.erb
watch these movies in the nude:
    <ul>
        <li><%= link_to @jesus_shows[0], answers_path %></li>
        <li><%=@jesus_shows[1] %></li>
        <li><%=@jesus_shows[2] %></li>
    </ul>